_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
architecture:
    value: cross
dataset:
    value: local
epochs:
    value: 4
learning_rate:
    value: 0.0001
train_size:
    value: null
valid_size:
    value: null
